version: '3'

services:
  jenkins:
    image: jenkins/jenkins:2.452.3-jdk17
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
      - "3000:3000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    container_name: jenkins-docker
    restart: unless-stopped

volumes:
  jenkins_home:
